services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.5.1
    container_name: mlflow
    env_file:
      - .env
    environment:
      - RUNNING_IN_DOCKER=1
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/mlflow
      - ./mlflow/mlruns:/mlruns
      - ./mlflow/mlartifacts:/mlartifacts
    command: >
      mlflow server
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --host 0.0.0.0
      --port 5000
      --allowed-hosts "*"
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3030:3000"
    environment:
      - RUNNING_IN_DOCKER=1
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
