global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'ml_monitoring'
    static_configs:
      - targets: ['fastapi:8000'] # If both fastapi and prometheus are running in a docker in same machine else use the fastapi url