name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          command_timeout: 30m
          script: |
            set -e
            cd /home/${{ secrets.AZURE_USER }}/mlops_churn_prediction
            echo "Pulling latest code"
            git pull origin main

            echo "Building new containers"
            docker compose -f docker-compose.yml build

            echo "Starting new containers"
            docker compose -f docker-compose.yml up -d --no-deps --build

            echo "Cleaning old containers"
            docker image prune -af

            echo "Deployment complete"
